### ISSUE TITLE
存储类型为csi-ssd-enterprise，执行扩容磁盘，报无法在线扩容

### ISSUE THREAD

**Issue by qianfen2021** [radondb/multi-platform-postgresql#16]
存储类型为csi-ssd-enterprise，执行扩容磁盘，报无法在线扩容，报错信息如下：
<img width="934" alt="a8c6c13079a924d969bfc4b9b8112c7" src="https://user-images.githubusercontent.com/86407305/203716308-a532e187-71e5-44cb-9726-9ef10ff973fe.png">

**Comment by yanboer** [comment]
This bug is fixed in [#14](https://github.com/radondb/multi-platform-postgresql/pull/14)
